version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      OPS: "pacogamer777"
      SERVER_NAME: "PacoServer"
      ONLINE_MODE: "FALSE"
      MOTD: "Bienvenido a Paco Server"
      MAX_MEMORY: 3G
      TYPE: "FORGE"
      #ENABLE_AUTOPAUSE: "TRUE"
      #OVERRIDE_SERVER_PROPERTIES: "TRUE"
    volumes:
      - ./data:/data
  dynamic_dns:
    build: dynamic_dns
    restart: unless-stopped
    env_file:
      - dynamic_dns.env
