version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      OPS: "pacogamer777"
      SERVER_NAME: "PacoServer"
      ONLINE_MODE: "FALSE"
      MOTD: "Bienvenido a Paco Server"
    volumes:
      - ./data:/data

